### ISSUE TITLE
Crashes if no `custom` is present

### ISSUE THREAD

**Issue by amir-ziaei** [baemingo/serverless-tscpaths#10]
If the serverless config doesn't have `custom`, the `tspaths` plugin crashes. I believe it's due to this line:
https://github.com/baemingo/serverless-tscpaths/blob/master/index.ts#L33

The plugin shouldn't assume everyone uses `custom`.

**Comment by tgrades** [comment]
Fixed here https://github.com/baemingo/serverless-tscpaths/pull/7

**Comment by amir-ziaei** [comment]
> Fixed here #7

Thank! Has this been successfully published to NPM? I am currently using version `^0.0.7`, but still encountering the issue. Upon examining the compiled source code, it seems that the ternary check is missing on L56:
https://www.npmjs.com/package/serverless-tscpaths/v/0.0.7?activeTab=explore

**Comment by tgrades** [comment]
Sorry for a late response. Yes, you are right. The proper code wasn't published.

**Comment by tgrades** [comment]
@amir-ziaei Hey I published version 0.0.8 with the fix. Can you see if works now?

**Comment by amir-ziaei** [comment]
> @amir-ziaei Hey I published version 0.0.8 with the fix. Can you see if works now?

Looks good now. Thanks!
